name: First_WorkFlow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: message
              run: |
                echo "This is to learn upload and download of artifacts" >> message.txt
                ls -l
            - name: upload-message file
              uses: actions/upload-artifact@v4
              with:
                name: my-mesage-file
                path: message.txt
                
    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
            - name: "Download file"            
              uses: actions/download-artifact@v4
              with:
                name: my-mesage-file
            - name: read the file
              run: cat message.txt
