name: First Workflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v4
      - name: print greeting
        run: echo "Hellow World"
      - name: print goodbyee
        run: echo "Done -Bye!"

      - name: read file
        run: cat README.md