name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hellow World"
      - name: print goodbyee
        run: echo "Done -Bye!"
